package me.anisimov.teachingAccounting.domain.Enums;

public enum ActivityType {

    ACTUALIZATION,
    DOCUMENTATION_MANAGEMENT,
    CRAFTING_OR_FIXING,
    DEVELOPMENT,
    DEVELOPMENT_WORK_GROUP,
    ORGANIZATION_FOR_PC_PCK,
    PROVIDENCE,
    PARTICIPATION,
    PARTICIPATION_PREPARE,
    MANAGEMENT_OF_INTERNSHIPS_FOR_STUDENTS_IN_HIGHER_EDUCATION_PROGRAMS,
    REALIZATION,
    ORGANIZATION,
    JOINT_ORGANIZATION

}
