package me.anisimov.teachingAccounting.domain.Enums;

public enum EventType {

    INTERNET_TESTING_FEPO,
    INTERNET_TESTING_TRAINERS,
    OPEN_DAY,
    QUEST_GAME,
    SUBJECT_GROUP_WORK,
    INTERNET_TESTING_INTERNET_OLIMPIADA,
    LAB_LESSONS_BASED_ON_MGTU,
    OPEN_EDUCATION_LESSON,
    OPEN_EVENT,
    PRACTICE_RESULT_EVENT,
    EMPLOYMENT_ASSISTANCE_EVENT_FOR_ALUMNI,
    PROFESSIONAL_SKILLS_COMPETITION_IN_THE_PROFESSION_OF_A_WORKER_OR_EMPLOYEE,
    PROFESSIONAL_SKILLS_OLYMPIAD_IN_SPECIALITY,
    PROFESSIONAL_SKILLS_COMPETITION_IN_THE_COMPETENCE,
    PROFESSIONAL_AUDITIONS,
    OLIMPIADA,
    COMPETITION,
    STUDENT_CONFERENCE,
    OPEN_DEFENCE_OF_COURSE_PROJECTS_OR_WORKS,
    EMPLOYER_MEETING,
    EXCURSION_TO_THE_ENTERPRISE_BY_SPECIALITY,
    CAMPAIGNING_AND_CAREER_GUIDANCE_AT_PARENT_MEETING_AT_SCHOOL,
    ADDITIONAL_PROFESSIONAL_PROGRAM_TRAINING,
    ADDITIONAL_EDUCATION_PROGRAM,
    DEMONSTRATION_EXAM_OF_COMPETENCE,
    INDIVIDUAL_SUPPORT_PROGRAM_FOR_DISABLED_STUDENT,
    MASTERCLASS,
    DIAGNOSTIC_TESTING,
    ROUND_TABLE,
    MARATHON,

    //Вид мероприятия воспитательной работы

    ACTION,
    VICTORINE,
    MEETING,
    EXHIBIT,
    VISITING,
    STUDENT_ACTIVE,
    //MARATHON - 34
    CLASS_HOUR,
    //COMPETITION - 21
    CONFERENCE,
    CONCERT,
    //ROUND_TABLE - 33
    LECTORY,
    //MASTERCLASS - 31
    FORUM,
    SOCIAL_HELPFUL_WORK,
    //OLIMPIADA - 20
    LESSON,
    HISTORICAL_PARADE_MARCH,
    GTO_STANDARTS_CHECK,
    TOURNAMENT,
    SPARTAKIAD,
    FEAST,
    TRAINING,
    STUDENT_ASSOCIATION,
    CHATTING_HOURS,
    PROJECT,
    EXCURSION,
    GAME,
    CONSUMER,
    SPORT_SECTION,
    SATURDAY_WORK,
    SCHOOL_OF_SOCIAL_DESIGN,
    DICTANT

}
