package me.anisimov.teachingAccounting.domain.Enums;

public enum PromotionForm {

    PARTICIPATION_IN_THE_INTRA_COLLEGE_EDUCATION_SYSTEM_ACTIVITIES,
    QUALIFICATION_PROMOTION_COURSES_STUDYING,
    ATTESTATION,
    ONLINE_COURSES,
    STAGING,
    ASPIRANTHUR,
    MAGISTRATURE,
    PROFESSIONAL_RETRAINING,

}
