package me.anisimov.teachingAccounting.domain.Enums;

public enum WorkVector {

    PROFESSIONAL_ORIENTATED,
    CIVIL_PATRIOTIC,
    CULTURE_CREATIVE,
    SPORTS_AND_HEALTHCARE,
    ECOLOGIC,
    STUDENT_SELF_ADMINISTRATION_DEVELOPMENT,
    PREVENTION_OF_UNLAWFUL_BEHAVIOR,
    LABOR,
    CONTINGENT_SAFETY

}
